FROM ubuntu:latest

RUN apt-get update && apt-get -y install libcairo2-dev cmake python2.7 python-pip git
RUN pip install pycairo

WORKDIR /fantasy_map_generator
RUN git clone https://github.com/rlguy/FantasyMapGenerator.git .
WORKDIR build
RUN cmake ..
RUN make
VOLUME /share